export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const USER_INFO_REQUEST = 'USER_INFO_REQUEST';
export const USER_INFO_FAILED = 'USER_INFO_FAILED';
export const USER_INFO_SUCCESS = 'USER_INFO_SUCCESS';

export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_FAILED = 'REGISTRATION_FAILED';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';